apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-burner
  namespace: chaos-engineering
spec:
  mode: one
  selector:
    namespaces:
      - chaos-engineering
  stressors:
    cpu:
      workers: 4
      load: 95
  duration: '120s'