apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: chaos-engineering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.50.0
        ports:
        - containerPort: 9090